name: LessIsMore
version: 1.1.0
api:
- 3.2.0
author: SOFe
main: SOFe\LessIsMore\LessIsMore
description: A simple plugin that lets you create new commands with your own message responses

permissions:
  lessismore:
    description: Root permission node for commands created with LessIsMore
